# TP3 - Hidden Markov Model (HMM)


### ING5, BDA02
- ABUL KALAM Simon : [simon.abulkalam@edu.ece.fr](mailto:simon.abulkalam@edu.ece.fr)
- BARITEAU Yanis : [yanis.bariteau@edu.ece.fr](mailto:yanis.bariteau@edu.ece.fr)
- PUY Guillaume : [guillaume.puy@edu.ece.fr](mailto:guillaume.puy@edu.ece.fr)

# Libraries Importation

In [1]:
import numpy as np

# Declaration of Variables

In [2]:
a = np.array([[1,0,0,0],[0.2,0.3,0.1,0.4],[0.2,0.5,0.2,0.1],[0.7,0.1,0.1,0.1]]) # Transition Probabilities
b = np.array([[1,0,0,0,0],[0,0.3,0.4,0.1,0.2],[0,0.1,0.1,0.7,0.1],[0,0.5,0.2,0.1,0.2]]) # Emission Probabilities

N = 3
T = 4

sequence_k = np.array([1,3,2,0]) #Sequence

# 1. Evaluation Problem

In [3]:
def evaluation(N:int, T:int, a, b, sequence_k):
    alpha = np.zeros(shape=(N+1,T+1))
    alpha[:,0] = [0,1,0,0]

    for t in range(1, T+1):
        for j in range(0, N+1):
            alpha[j,t] = sum( alpha[i,t-1]*a[i,j]*b[j,sequence_k[t-1]] for i in range(1,N+1) )
    
    print(alpha)
    return alpha[0, T]

In [4]:
P_X_given_M = evaluation(N,T,a,b,sequence_k)
print(f"\nP(X | M) = {P_X_given_M}")

[[0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 1.8218e-03]
 [1.0000e+00 9.0000e-02 5.2000e-03 5.1920e-03 0.0000e+00]
 [0.0000e+00 1.0000e-02 2.1700e-02 5.4300e-04 0.0000e+00]
 [0.0000e+00 2.0000e-01 5.7000e-03 9.6400e-04 0.0000e+00]]

P(X | M) = 0.0018218000000000002


# 2. Decoding Problem

In [5]:
def decoding(N:int, T:int, a, b, sequence_k):
    alpha = np.zeros(shape=(N+1,T+1))
    alpha[:,0] = [0,1,0,0]
    path = [f'Z{sequence_k[0]}']

    for t in range(1, T+1):
        for j in range(0, N+1):
            alpha[j,t] = sum( alpha[i,t-1]*a[i,j]*b[j,sequence_k[t-1]] for i in range(1,N+1) )
        path.append(f'Z{np.argmax(alpha[:,t])}')

    return path

In [6]:
path = decoding(N,T,a,b,sequence_k)
print(path)

['Z1', 'Z3', 'Z2', 'Z1', 'Z0']
